name: 'Deploy'

on:
  push:
    branch:
      - main

jobs:
  deploy-int:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment:
      name: int
    steps:
      - name: Fake Deploy
        run:  echo "Fake deploy!""

      # - name: 'Git checkout'
      #   uses: actions/checkout@v3
      #   with:
      #     ref: main

      # - name: Set up node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 16

      # - name: Install dependencies
      #   uses: bahmutov/npm-install@v1

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2

      # - name: Deploy
      #   run: npx sst deploy --stage int --outputs-file out.json

      # - name: Upload logs to artifactory
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: deploy-output
      #     path: out.json
  run-tests-int:
    name: 'Run tests'
    runs-on: ubuntu-latest
    container: 'cypress/browsers:node18.12.0-chrome107'
    needs: deploy-int
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v3
        with:
          ref: main
      - name: 'Run Percy&Cypress'
        uses: cypress-io/github-action@v5
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        with:
          working-directory: tests
          command: npm run percy:int
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: tests/cypress/reports/html
  deploy-prod:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs: run-tests-int
    steps:
      - name: Fake Deploy
        run:  echo "Fake deploy!""

      # - name: 'Git checkout'
      #   uses: actions/checkout@v3
      #   with:
      #     ref: main

      # - name: Set up node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 16

      # - name: Install dependencies
      #   uses: bahmutov/npm-install@v1

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2

      # - name: Deploy
      #   run: npx sst deploy --stage int --outputs-file out.json

      # - name: Upload logs to artifactory
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: deploy-output
      #     path: out.json
  run-tests-prod:
    name: 'Run tests'
    runs-on: ubuntu-latest
    container: 'cypress/browsers:node18.12.0-chrome107'
    needs: deploy-prod
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v3
        with:
          ref: main
      - name: 'Run Percy&Cypress'
        uses: cypress-io/github-action@v5
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        with:
          working-directory: tests
          command: npm run percy:prod
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: tests/cypress/reports/html