name: 'Test'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment under tests

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v4

      - name: Run Percy&Cypress
        uses: cypress-io/github-action@v6
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
        with:
          command-prefix: percy exec -- npx
          working-directory: tests
          browser: chrome
          config-file: cypress/config/${{ inputs.environment }}.ts
          component: false
