name: 'Deploy'

on:
  workflow_dispatch:

jobs:
  run-tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    container: 'cypress/browsers:node18.12.0-chrome107'
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v3
        with:
          ref: main
      - name: 'Run Percy&Cypress'
        uses: cypress-io/github-action@v5
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        with:
          command: npm run percy:dev
          config: baseUrl=http://localhost:3000
