name: 'Test'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment under tests

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v4

      - name: Run Percy&Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: tests
          browser: chrome
          config-file: cypress/config/${{ inputs.environment }}.ts
          component: false
