name: 'Test'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment under tests

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v4
        with:
          ref: vol-3-preparations
      - name: Run Percy&Cypress
        uses: cypress-io/github-action@v6
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: tests
          browser: chrome
          config-file: cypress/config/${{ inputs.environment }}.ts
          component: false
          record: true
          parallel: true
          publish-summary: false
